package lt.vu.usecases.mybatis.model;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.authors.id
     *
     * @mbg.generated Sun Apr 07 17:44:28 EEST 2019
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.authors.id
     *
     * @return the value of public.authors.id
     *
     * @mbg.generated Sun Apr 07 17:44:28 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.authors.id
     *
     * @param id the value for public.authors.id
     *
     * @mbg.generated Sun Apr 07 17:44:28 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }
}