package lt.vu.usecases.mybatis.model;

public class BookAuthor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.books_authors.book_id
     *
     * @mbg.generated Sun Apr 07 17:44:28 EEST 2019
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.books_authors.author_id
     *
     * @mbg.generated Sun Apr 07 17:44:28 EEST 2019
     */
    private Integer authorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.books_authors.book_id
     *
     * @return the value of public.books_authors.book_id
     *
     * @mbg.generated Sun Apr 07 17:44:28 EEST 2019
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.books_authors.book_id
     *
     * @param bookId the value for public.books_authors.book_id
     *
     * @mbg.generated Sun Apr 07 17:44:28 EEST 2019
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.books_authors.author_id
     *
     * @return the value of public.books_authors.author_id
     *
     * @mbg.generated Sun Apr 07 17:44:28 EEST 2019
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.books_authors.author_id
     *
     * @param authorId the value for public.books_authors.author_id
     *
     * @mbg.generated Sun Apr 07 17:44:28 EEST 2019
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }
}