version: '3'

services:
  db:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - .database_data:/var/lib/postgresql/data
  tomee:
    image: marsas/tomee7-with-hibernate5
    ports:
      - 8080:8080
    volumes:
      - ./target/JavaEEstarter-1.0-SNAPSHOT.war:/usr/local/tomee/webapps/JavaEEstarter-1.0-SNAPSHOT.war