package lt.vu.usecases.mybatis.dao;

import java.util.List;
import lt.vu.usecases.mybatis.model.BookAuthor;
import org.mybatis.cdi.Mapper;

@Mapper
public interface BookAuthorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.books_authors
     *
     * @mbg.generated Sun Apr 07 17:44:28 EEST 2019
     */
    int insert(BookAuthor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.books_authors
     *
     * @mbg.generated Sun Apr 07 17:44:28 EEST 2019
     */
    List<BookAuthor> selectAll();
}